kafka:
  bootstrap_servers: kafka:9092
  topic_user: "mysql_server.source_db.users"
  topic_nyc_taxi: "mysql_server.source_db.nyc_taxi"
  group_id: 'cdc-consumer-group'
  max_offsets_per_trigger: 50000
  starting_offsets: "earliest"
  fail_on_data_loss: false
  min_partitions: 3



postgres:
  url: 'jdbc:postgresql://postgres:5432/target_db'
  user: 'postgresuser'
  password: 'postgrespass'
  table_user: 'public.users'
  table_nyc_taxi: 'public.nyc_taxi'
  driver: 'org.postgresql.Driver'
  batch_size: 5000
 


spark:
  master: "spark://spark:7077"
  app_name: "cdc_mysql_to_postgres"
  executor_memory: "2g"
  executor_cores: 2 
  default_parallelism: 8
  shuffle_partitions: 8
  checkpoint_location: "/tmp/checkpoint"

schema_user:
  columns:
    - name: id
      type: IntegerType
    - name: name
      type: StringType
    - name: email
      type: StringType
    - name: created_at
      type: TimestampType


schema_nyc_taxi:
  columns:
    - name: id
      type: IntegerType
    - name: VendorID
      type: IntegerType
    - name: tpep_pickup_datetime
      type: TimestampType
    - name: tpep_dropoff_datetime
      type: TimestampType
    - name: passenger_count
      type: FloatType
    - name: RatecodeID
      type: FloatType
    - name: trip_distance
      type: FloatType
    - name: store_and_fwd_flag
      type: StringType
    - name: PULocationID
      type: IntegerType
    - name: DOLocationID
      type: IntegerType
    - name: payment_type
      type: IntegerType
    - name: fare_amount
      type: FloatType
    - name: extra
      type: FloatType
    - name: mta_tax
      type: FloatType
    - name: tip_amount
      type: FloatType
    - name: tolls_amount
      type: FloatType
    - name: improvement_surcharge
      type: FloatType
    - name: total_amount
      type: FloatType
    - name: congestion_surcharge
      type: FloatType
    - name: Airport_fee
      type: FloatType
    - name: created_at
      type: TimestampType
    - name: status_delete 
      type: BooleanType
    - name: delete_at
      type: TimestampType